config/routes.rb
Rails.application.routes.draw do

  root 'categories#index'

  resources :categories
  resources :products
  resources :players
  resources :users
  resources :reviews

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :carts, only: [:index, :update, :destroy]
  resources :games, only: [:index]
  resources :orders
  
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/player.rb
class Player < ActiveRecord::Base

  validates :name,  presence: true
  validates :number,  presence: true

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.all
    @players = @players.limit(100)
  end

  def show
    @player = Player.find_by(id: params[:id])
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new
    @player.number = params[:player][:number]
    @player.name = params[:player][:name]
    @player.position = params[:player][:position]
    @player.height = params[:player][:height]
    @player.weight = params[:player][:weight]
    @player.age = params[:player][:age]
    @player.birthplace = params[:player][:birthplace]
    @player.image_url = params[:player][:image_url]
    @player.acquired = params[:player][:acquired]
    @player.drafted = params[:player][:drafted]
    @player.round = params[:player][:round]
    if @player.save
      redirect_to players_url, notice: "New player added"
    else
      render 'new'
    end
  end

  def edit
    @player = Player.find_by(id: params[:id])
  end

  def update
    player = Player.find_by(id: params[:id])
    player.name = params[:player][:name]
    player.number = params[:player][:number]   
    player.position = params[:player][:position]
    player.height = params[:player][:height]
    player.weight = params[:player][:weight]
    player.age = params[:player][:age]
    player.birthplace = params[:player][:birthplace]
    player.image_url = params[:player][:image_url]
    player.acquired = params[:player][:acquired]
    player.drafted = params[:player][:drafted]
    player.round = params[:player][:round]
    player.save
    redirect_to player_url(player)
  end

  def destroy
    player = Player.find_by(id: params[:id])
    player.delete
    redirect_to players_url
  end
  
end

app/views/players/_form.html.erb
<%= @player.errors.full_messages %>

<%= form_for @player do |form| %>

  <p><%= form.label :name %>
  <br>
  <%= form.text_field :name, size: 80, autofocus: true, required: true %></p>

  <p><%= form.label :number %>
  <br>
  <%= form.text_field :number %></p>
  
  <p><%= form.label :position %>
  <br>
  <%= form.text_field :position %></p>


  <p><%= form.label :height %>
  <br>
  <%= form.text_field :height %></p>


  <p><%= form.label :weight %>
  <br>
  <%= form.text_field :weight %></p>

  <p><%= form.label :age %>
  <br>
  <%= form.text_field :age %></p>

  <p><%= form.label :birthplace %>
  <br>
  <%= form.text_field :birthplace, size: 80 %></p>


  <%= form.label :image_url,  "Link to player URL" %>
  <br>
  <%= form.text_field :image_url %>


  <p><%= form.label :acquired %>
  <br>
  <%= form.text_field :acquired, size: 80 %></p>

  <p><%= form.label :drafted %>
  <br>
  <%= form.text_field :drafted, size: 80 %></p>


  <%= form.label :round %>
  <br>
  <%= form.text_field :round, size: 80 %>
  <br>
  <br>
  

  <%= form.submit :class => 'form_button' %>

<% end %>

app/views/players/edit.html.erb
<div class=container3>

<h2>Edit Player: <%= @player.name %></h2>

<%= render 'form' %>

</div>

app/views/players/index.html.erb
<h1>Players</h1>


<div class="table_page">

<% if session["user_id"].present? %>
  <% current_user = User.find_by(id: session["user_id"]) %>
  <% if current_user.admin %>
    <h3>
    <%= link_to "Add Player", new_player_path %>
    </h3>
   <% end %>
 <% end %>

 </div>



<table>
  <tr>
    <th>Number</th>
    <th>Name</th>
    <th>Position</th>
    <th><Height</th>
    <th>Weight</th>
    <th>Age</th>
    <th>Birth Place</th>
  </tr>


<% @players.each do |player| %>

  <tr>
  	<td><%= player.number %></td> 
  	<td><%= link_to player.name, "/players/#{player.id}" %></td>
  	<td><%= player.position %></td> 
  	<td><%= player.height %></td> 
  	<td><%= player.weight %></td> 
  	<td><%= player.age %></td> 
  	<td><%= player.birthplace %></td>
  </tr>	

<% end %>

</table>

app/views/players/new.html.erb
<div class=container3>

<h2>Add Player</h2>

<%= render 'form' %>

</div>

app/views/players/show.html.erb
<h1>
  <%= @player.name %>

<% if session["user_id"].present? %>
  <% current_user = User.find_by(id: session["user_id"]) %>
  <% if current_user.admin %>
  <small>
    <%= link_to "Edit This Player", edit_player_path(@player.id) %>
    <%= link_to "Delete This Player", player_path(@player.id), :method => :delete %>
  </small>
   <% end %>
 <% end %>

</h1>

<div class="player_details">

  <p><%= image_tag @player.image_url, class: 'pull-left' %></p>

  <div class="player_stats">
    <p><strong>Number</strong> <%= @player.number %></p>
    <p><strong>Position</strong> <%= @player.position %></p>
    <p><strong>Height</strong> <%= @player.height %></p>
    <p><strong>Weight</strong> <%= @player.weight %></p>
    <p><strong>Age</strong> <%= @player.age %></p>
    <p><strong>Birthplace</strong> <%= @player.birthplace %></p>
    <p><strong>Acquired</strong> <%= @player.acquired %></p>
    <p><strong>Drafted</strong> <%= @player.drafted %></p>
    <p><strong>Round</strong> <%= @player.round %></p>
  </div>

</div>