config/routes.rb
Rails.application.routes.draw do

  root 'categories#index'

  resources :categories
  resources :products
  resources :players
  resources :users
  resources :reviews

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :carts, only: [:index, :update, :destroy]
  resources :games, only: [:index]
  resources :orders
  
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    category = Category.find_by(id: params[:id])
    @products = category.products
  end

  def new

  end

  def create
    category = Category.new
    category.name = params[:name]
    category.save
    redirect_to categories_url
  end

  def edit
    @category = Category.find_by(id: params[:id])
  end

  def update
    category = Category.find_by(id: params[:id])
    category.name = params[:name]
    category.save
    redirect_to categories_url
  end

  def destroy
    category = Category.find_by(id: params[:id])
    category.delete
    redirect_to categories_url
  end
  
end

app/views/categories/index.html.erb
<h1>Merchandise</h1>

<div class=categories>

<ul>
<% @categories.each do |category| %>
  <li><%= link_to category.name, "/categories/#{category.id}" %></li>
<% end %>
</ul>


</div>

app/views/categories/show.html.erb
<div class="table_page">

<% if session["user_id"].present? %>
  <% current_user = User.find_by(id: session["user_id"]) %>
  <% if current_user.admin %>
    <h3>
    <%= link_to "Add Product", new_product_path %>
    </h3>
   <% end %>
 <% end %>

 </div>

<% @products.each do |product| %>

  <div class="product-box">
    <%= link_to image_tag(product.image_url), product_path(product.id) %>
    <h3><%= link_to product.name, product_path(product.id) %></h3>
  </div>

<% end %>