config/routes.rb
Rails.application.routes.draw do

  root 'categories#index'

  resources :categories
  resources :products
  resources :players
  resources :users
  resources :reviews

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :carts, only: [:index, :update, :destroy]
  resources :games, only: [:index]
  resources :orders
  
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :category  #, foreign_key: :category_id, class_name: "Category"

  has_many :contains_products  #, foreign_key: :shopping_cart_id, class_name: 'ContainsProduct'
  has_many :carts, :through => :contains_products

  # reviews = Review.where(product_id: @product.id)
  has_many :reviews, :dependent => :nullify 

  validates :name,  presence: true
  validates :price,  presence: true
  validates :category_id,  presence: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    @products = @products.limit(1000)
  end

  def show
    @product = Product.find_by(id: params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new
    @product.name = params[:product][:name]
    @product.price = params[:product][:price]
    @product.description = params[:product][:description]
    @product.image_url = params[:product][:image_url]
    @product.category_id = params[:product][:category_id]
    if @product.save
      redirect_to category_url(@product.category_id), notice: "New product added"
    else
      render 'new'
    end   
  end


  def edit
    @product = Product.find_by(id: params[:id])
  end


  def update
    product = Product.find_by(id: params[:id])
    product.name = params[:product][:name]
    product.price = params[:product][:price]
    product.description = params[:product][:description]
    product.image_url = params[:product][:image_url]
    product.category_id = params[:product][:category_id]
    product.save
    redirect_to product_url(product.id)
  end


  def destroy
    product = Product.find_by(id: params[:id])
    product.delete
    redirect_to category_url(product.category_id)
  end
  
end

app/views/products/_form.html.erb
<%= @product.errors.full_messages %>

<%= form_for @product do |form| %>

  <p><%= form.label :name %>
  <br>
  <%= form.text_field :name, size: 80, autofocus: true, required: true %></p>

  <p><%= form.label :price %>
  <br>
  <%= form.text_field :price %></p>
  
  <p><%= form.label :description %>
  <br>
  <%= form.text_field :description, size: 80 %></p>

  <%= form.label :image_url,  "Link to product URL" %>
  <br>
  <%= form.text_field :image_url %>


  <p><%= form.label :category_id, "Category" %>
  <br>
  <%= form.collection_select :category_id, Category.all.order('name'), :id, :name %></p>
  <br>
  <br>
  

  <%= form.submit :class => 'form_button' %>

<% end %>

app/views/products/edit.html.erb
<div class=container3>

<h2>Edit Product: <%= @product.name %></h2>

<%= render 'form' %>

</div>

app/views/products/new.html.erb
<div class=container3>

<h2>Add Product</h2>

<%= render 'form' %>

</div>

app/views/products/show.html.erb
<div class="details">

<h2>
  <%= @product.name %>

  <% if session["user_id"].present? %>
    <% current_user = User.find_by(id: session["user_id"]) %>
   <% if current_user.admin %>
      <small>
        <%= link_to "Edit This Product", edit_product_path(@product.id) %>
        <%= link_to "Delete This Product", product_path(@product.id), :method => :delete %>
      </small>
    <% end %>
 <% end %>
</h2>

  <p><%= image_tag @product.image_url, class: 'pull-left' %></p>
  <p><%= link_to "Add to Cart", cart_path(@product.id), :method => :patch, class: 'pull-right' %></p>

  <p><strong>Price:</strong> <%= number_to_currency @product.price/100.00 %></p>
  <p><strong>Description:</strong> <%= @product.description %></p>


<div class=reviews>

  <h4>Add a Review</h4>

  <%= form_tag "/reviews", :method => :post do %>

    <select name="rating">
    <option>5 star</option>
    <option>4 star</option>
    <option>3 star</option>
    <option>2 star</option>
    <option>1 star</option>
    </select>
  
    <%= hidden_field_tag :product_id, @product.id %>  
    <br>
    <%= text_area_tag :body, '', rows: 4, cols: 50 %>
    <br>
    <%= submit_tag "Add Review" %>
  <% end %>


  <h3>Reviews</h3>

  <ul>
    <% @product.reviews.each do |review| %>

    <p>    
      <strong><%= ("&#9733;" * review.rating).html_safe  %></strong>
      <%= review.body %>
    </p>

    <% end %>
  </ul>

  </div>

  </div>