config/routes.rb
Rails.application.routes.draw do

  root 'categories#index'

  resources :categories
  resources :products
  resources :players
  resources :users
  resources :reviews

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :carts, only: [:index, :update, :destroy]
  resources :games, only: [:index]
  resources :orders
  
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" type="image/x-icon" href="http://cdn.nhle.com/blackhawks/v2/images/favicon.ico"></link>
</head>
<body>

  <nav>
    <ul>
      <li><%= link_to "Players", players_url %></li>
      <li><%= link_to "Schedule", games_url %></li>
      <li><%= link_to "Merchandise", categories_url %></li>

      <% if session["user_id"].present? %>
      <% current_user = User.find_by(id: session["user_id"]) %>
        <% if current_user.admin %>
          <li><%= link_to "Users", users_url %></li>
          <li><%= link_to "Orders", orders_url %></li>
        <% end %>
      <% end %>

    </ul>

    <ul class="nav-right">
      <% if session["user_id"].present? %>
        <% current_user = User.find_by(id: session["user_id"]) %>
        <li>Hello, <%= link_to current_user.name, user_path(current_user) %>!</li>
        <li><%= link_to image_tag("shopping_cart2.png"), carts_path %></li>
        <li><%= link_to "Sign Out", logout_path %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_path %></li>
        <li><%= link_to "Sign In", login_path %></li>
      <% end %>
    </ul>

  </nav>



  <div>

    <% if flash["notice"].present? %>
    <h3><%= flash["notice"] %></h3>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>